// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// locpoly
Eigen::VectorXd locpoly(Eigen::MatrixXd original_points);
RcppExport SEXP _localweightedreg_locpoly(SEXP original_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type original_points(original_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(locpoly(original_points));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_localweightedreg_locpoly", (DL_FUNC) &_localweightedreg_locpoly, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_localweightedreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
