# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

locpoly <- function(original_points, epsilon, bandwidth, method, N_min, kcode) {
    .Call('_localweightedreg_locpoly', PACKAGE = 'localweightedreg', original_points, epsilon, bandwidth, method, N_min, kcode)
}

